# Starting Deep learning with percetron

In [1]:
import torch
import torch.nn as nn

In [2]:
# Input
inputs=torch.tensor([1.0,2.0,3.0])
neuron=nn.Linear(in_features=3,out_features=1)

In [3]:
# Find weigth
neuron.weight
neuron.bias

Parameter containing:
tensor([0.0758], requires_grad=True)

In [4]:
output=neuron(inputs)
output

tensor([0.1020], grad_fn=<ViewBackward0>)

In [5]:
# Verify .... formula of weighted sum
neuron.weight@inputs+neuron.bias

tensor([0.1020], grad_fn=<AddBackward0>)