# Arrays Properties

In [1]:
import numpy as np
arr=np.array([[1,4,5],[7,8,4],[8,9,4]])
print(arr.shape)

(3, 3)


In [2]:
print(arr.size)

9


In [4]:
print(arr.dtype)

int64


In [5]:
print(arr.ndim)

2


In [10]:
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[[1. 4. 5.]
 [7. 8. 4.]
 [8. 9. 4.]] float64
