# Creating Arrays Using Built In Method

- ( Prefill ) Zero Matrix

In [1]:
import numpy as np
arr1=np.zeros((2,3))
print(f"{arr1}{arr1.shape}")

[[0. 0. 0.]
 [0. 0. 0.]](2, 3)


- ( Prefill ) Ones Matrix

In [2]:
arr2=np.ones((5,))
print(f"{arr2}{arr2.shape}")

[1. 1. 1. 1. 1.](5,)


-  Prefill With Value

In [3]:
arr3=np.full((3,5),100)
print(f"{arr3}{arr3.shape}")

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]](3, 5)


- Indentity Matrix

In [4]:
arr4=np.eye(3)
print(f"{arr4}{arr4.shape}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]](3, 3)


- Arrange Identity Matrix

In [5]:
arr5=np.arange(0,11,2)       # work like range
print(f"{arr5}{arr5.shape}")

[ 0  2  4  6  8 10](6,)


- Evenly Space Matrix

In [10]:
arr6 = np.linspace(0,100,5,dtype="int64")     # line space work covers 100 in 5 steps
print(arr6,arr6.shape)


[  0  25  50  75 100] (5,)
