# List To Array

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype) # dtype tell us what type of array it is like it is of type Intefer (int64)
print(arr,type(arr),arr.shape) # tell us the size of the array


# Homogenious in nature 

arr2=np.array([1,2,3,4,5,"numpy"])
print(arr2,type(arr2),arr2.dtype) # dtype tell us what type of array it is like it is of type string (U21)
print(arr2,type(arr2),arr.shape)  # tell us the size of the array


[1 2 3 4 5] <class 'numpy.ndarray'> int64
[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'numpy'] <class 'numpy.ndarray'> <U21


In [14]:
arr3=np.array([[7,8,9],[4,5,6],[1,2,3]])
print(f"{arr3} \n{type(arr3)}\n{arr3.dtype}\n{arr3.shape}") 


[[7 8 9]
 [4 5 6]
 [1 2 3]] 
<class 'numpy.ndarray'>
int64
(3, 3)
