# Operations On Arrays

- Reshapping Arrays

In [15]:
import numpy as np
arr=np.array([[1,4,5],[8,9,5]])

print(f"Before Reshape: \n{arr}\n{arr.shape}")

print(f"After Reshape: \n{arr.reshape(3,2)}")


Before Reshape: 
[[1 4 5]
 [8 9 5]]
(2, 3)
After Reshape: 
[[1 4]
 [5 8]
 [9 5]]


In [16]:
arr_flatten=arr.flatten()
print(f"{arr_flatten} \n{arr_flatten.shape}")

[1 4 5 8 9 5] 
(6,)


# Indexing Arrays

 - Normal Indexing

In [50]:
arr1=np.array([[1,4,5],[8,9,7]])
print(arr1[1])
print(arr1[1][0])


[8 9 7]
8


- Fancy Indexing

In [51]:
idx=[1]
print(arr[idx])


[[8 9 5]]


- Boolean Indexing

In [56]:
arr2=np.array([7,8,5,4])
print(arr2[arr2%2==0])

[8 4]


- Slicing In Index  ( In Numpy while slicing Internally create view and in  list cretas a copy of the slicing array ) that's  the reason numpy is faster than list

In [65]:
print(arr2[::2])

[7 5]
