# Playing with 3D Array

In [1]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr,arr.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]] (2, 3, 3)


In [4]:
print(arr.sum(),arr.shape)


171 (2, 3, 3)


In [8]:
print(arr[1,2,1])


17


In [11]:
print(arr[:,:1,:2])


[[[ 1  2]]

 [[10 11]]]


In [16]:
arr3d=arr[:,:,:1]=50
print(arr)


[[[50  2  3]
  [50  5  6]
  [50  8  9]]

 [[50 11 12]
  [50 14 15]
  [50 17 18]]]
