# Multi Dimension Array

In [1]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Sum

In [2]:
print(np.sum(arr))
sum_of_columns=np.sum(arr,axis=0)
print(sum_of_columns)
sum_of_rows=np.sum(arr,axis=1)
print(sum_of_rows)

45
[12 15 18]
[ 6 15 24]


In [5]:
print(arr[:2,1:2])

[[2]
 [5]]
